task: kitti-360
exp_name: 'urbangiraffe_kitti360'
exp_comment: ''
is_debug: False
####

ratio: 0.5
super_resolution: 2
patch_size: 128
vertex_threshold: 5
rate_threshold: 0.25

trainer_type: urbangiraffe
dataset_train_type: urbangiraffe
dataset_test_type: urbangiraffe
network_type: urbangiraffe
loss_type: urbangiraffe
optimizer_type: urbangiraffe

####
render_obj: True
render_stuff: True
render_sky: True
use_occupancy_mask: True
use_patch_occupancy_mask: True
use_patch_discriminator: True

stuff_semantic_list: [
    'vegetation','terrain','ground','road', 'sidewalk','parking','rail track','building','gate','garage', 'bridge','tunnel','wall',
    'truck','train','caravan','bus','trailer',
    'fence','guard rail','trash bin','box','lamp','smallpole','polegroup','stop','pole','traffic sign','traffic light']
    
# Network

train:
    batch_size: 4
    optim: 'adam'
    lr: 2e-4
    lr_d: 1e-4
    weight_decay: 1e-4
    epoch: 300

    loss_weight:
        gan: 1.0
        l2: 10.0
        perceptual: 3.0
        gan_reg: 10.0
        gan_obj: 1.

    perceptual_loss:
        mode: 'vgg19'
        layers: ['relu_3_1', 'relu_4_1', 'relu_5_1']
        weights: [0.125, 0.25, 1.0]

    car_lr_mul: 1.
    building_lr_mul: 1.
    sky_lr_mul: 1.
    mapping_lr_mul: 0.1
    
    scheduler:
        type: 'exponential'
        gamma: 0.5
        decay_epochs: 100
    num_workers: 8
    use_trajectory: True
    shuffle: True
    #loss
