gpus: [0]
task: kitti-360
exp_name: 'urbangiraffe_kitti360'
exp_comment: ''
# distributed: True

is_debug: False
####
fix_random: True
z_far: 48
z_far_render: 64
ratio: 0.5
super_resolution: 2
patch_size: 128
vertex_threshold: 5
rate_threshold: 0.25

trainer_type: urbangiraffe
dataset_train_type: urbangiraffe
dataset_test_type: urbangiraffe
network_type: urbangiraffe
loss_type: urbangiraffe
optimizer_type: inversion

####
render_obj: False
render_stuff: True
render_sky: True
use_occupancy_mask: True
use_patch_occupancy_mask: False
use_patch_discriminator: False
use_depth: True

inversion: True

max_obj_num: 4
valid_object: ['car']
min_visible_pixel: 
    car : 3000
# Network
stuff_semantic_list: [
    'vegetation','terrain','ground','road', 'sidewalk','parking','rail track','building','gate','garage', 'bridge','tunnel','wall',
    # 'truck','train','caravan','bus','trailer',
    'fence','guard rail',
    # 'trash bin','box','lamp','smallpole','polegroup','stop','pole','traffic sign','traffic light'
    ]
    

# Network
network_kwargs:
    discriminator_type: 'StyleGAN2'
    discriminator_obj_type: 'StyleGAN2'
    generator_kwargs:
        obj_decoder_type: 'giraffe_ins'
        stuff_decoder_type: 'stuff'
        sky_decoder_type: 'sky'
        neural_renderer_type: 'eg3dNR'
        z_grid_generator_type: 'VolumeGenerator'
        n_vox_intersection: 6
        n_samples_stuff: 4
        n_samples_obj: 8
        n_vox_intersection_render: 12
        n_samples_stuff_render: 12
        n_samples_obj_render: 16
        ray_voxel_sampling: True
        use_neural_renderer: True
        sky_decoder_kwargs:
            in_channel: 3
            hidden_channel: 128
            out_channel: 64
            style_channel: 256
            n_block_num: 4
            use_positonal_encoding: True
            n_freq_posenc: 10
            final_tanh: False

        stuff_decoder_kwargs:
            in_channel: 3
            hidden_channel: 256
            out_channel: 64
            w_channel: 16
            style_channel: 512
            n_block_num: 4
            use_viewdirs: False
            use_seg: False
            use_positonal_encoding: True
            n_freq_posenc_pts: 10
            n_freq_posenc_w: 4
            n_freq_posenc_views: 4
            final_tanh: False

        z_grid_generator_kwargs:
            init_res : 4
            volume_res : [64,64,64]
            max_channel : 512
            out_channel : 32
            semantic_channel : 42
            spade_hidden_channel : 128
            data_normalize_type : 'instance'
            weight_normalize_type : 'equal_lr'
            noise_type : 'oasis'
            z_dim : 256
            z_dim_oasis : 64
            sparse_conv : False
            kernel_size : 3
            final_unconditional_layer : True
            final_tanh : False

        neural_render_kwargs:
            deep: True
            in_channel : 32
        
    discriminator_kwargs:
        init_res : 4
        max_channel : 256
    discriminator_obj_kwargs:
        init_res : 4
        max_channel : 256

render:
    ckpt_dir: '/data/jxhuang/experiments/urbangiraffe/trained_model/kitti-360/urbangiraffe_kitti360/None/24.pth'
    use_trajectory: True

test:
    batch_size: 1
    shuffle: False
    use_occupancy: True
    test_given_frame: True
    test_frame_list: [250, 260, 270, 280, 290, 300]
    use_trajectory: True

train:
    batch_size: 1
    optim: 'adam'
    lr: 1e-5
    lr_d: 2e-3
    weight_decay: 0.
    epoch: 300

    loss_weight:
        gan: 0.0
        l2: 1.
        l1_depth: 1.
        perceptual: 1.
        gan_reg: 0.0
        gan_obj: 0.0

    perceptual_loss:
        mode: 'vgg19'
        layers: ['relu_3_1', 'relu_4_1', 'relu_5_1']
        weights: [0.125, 0.25, 1.0]
    
    num_workers: 8
    use_trajectory: True
    shuffle: True
    #loss
train_dataset:
    seq_list: [0]
    # 'train', 'test', 'full'
    split: 'train'
    use_full: False

test_dataset:
    seq_list: [0]
    split: 'test'
    use_full: False

